version: "3.9"
services:
  cloudera1: &cloudera1
    container_name: cloudera1
    networks: [cloudera]
    build: .
    privileged: true
    volumes:
      - "./examples/local/id_rsa.pub:/root/.ssh/authorized_keys"

  cloudera0:
    <<: *cloudera1
    container_name: cloudera0
    ports:
      - "7180:7100"

  parcel-repo:
    <<: *cloudera1
    container_name: parcel-repo
    volumes:
      - "./examples/local/id_rsa.pub:/root/.ssh/authorized_keys"
      - "./repo:/var/www/html"

  cloudera-deploy:
    container_name: cloudera-deploy
    networks: [cloudera]
    image: "ghcr.io/cloudera-labs/cldr-runner:base-latest"
    volumes:
      - "./examples/local/id_rsa:/root/.ssh/id_rsa"
      - ".:/opt/cloudera-deploy/"
      - "${SSH_AUTH_SOCK}:/run/host-services/ssh-auth.sock"
      - "${HOME}/.aws:/home/runner/.aws"
      - "${HOME}/.config:/home/runner/.config"
      - "${HOME}/.ssh:/home/runner/.ssh"
      - "${HOME}/.cdp:/home/runner/.cdp"
      - "${HOME}/.azure:/home/runner/.azure"
      - "${HOME}/.kube:/home/runner/.kube"
    environment:
      SSH_AUTH_SOCK: "/run/host-services/ssh-auth.sock"
      ANSIBLE_LOG_PATH: "/home/runner/.config/cloudera-deploy/log/${CLDR_BUILD_VER:-latest}-$(date +%F_%H%M%S)"
      STRANGE_BUG: "$WHERE_IT_DOESNT_WORK_WITHOUT_DOLLAR"
      ANSIBLE_INVENTORY: "inventory"
      ANSIBLE_CALLBACK_WHITELIST: "ansible.posix.profile_tasks"
      ANSIBLE_GATHERING: "smart"
      ANSIBLE_DEPRECATION_WARNINGS: "false"
      ANSIBLE_HOST_KEY_CHECKING: "false"
      ANSIBLE_SSH_RETRIES: "10"
      ANSIBLE_COLLECTIONS_PATH: "/opt/cldr-runner/collections"
      ANSIBLE_ROLES_PATH: "/opt/cldr-runner/roles"
      AWS_DEFAULT_OUTPUT: "json"
    command: ["/usr/local/bin/ansible-playbook", "/opt/cloudera-deploy/main.yml", "-e", "definition_path=examples/local", "-t", "run,default_cluster"]
    depends_on:
      - cloudera0
      - cloudera1
      - parcel-repo

networks:
  cloudera:
    name: cloudera
